QuanLyNhanSu/Areas/admin/Controllers/QuanLyLuongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyNhanSu.Models;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Data;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class QuanLyLuongController : AuthorController
    //     public class QuanLyLuongController : AuthorController
    {
        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/QuanLyLuong/
        public ActionResult Index()
        {
            var list = db.Luongs.ToList();
            return View(list);
        }
        
        public ActionResult GetLuongByMonth(int month)
        {
            var luongList = db.ChiTietLuongs.Where(l => l.NgayNhanLuong.Month == month).ToList();
            return PartialView("_LuongTable", luongList);
        }
        [HttpGet]
        public ActionResult SuaBangLuong(String id)
        {
            var luong = db.Luongs.Where(n => n.MaNhanVien == id).SingleOrDefault();
            return View(luong);
        }
        [HttpPost]
        public ActionResult SuaBangLuong(Luong luong, CapNhatLuong up)
        {
            var l = db.Luongs.Where(n => n.MaNhanVien == luong.MaNhanVien).FirstOrDefault();
            if (l != null)
            {
                //  l.MaNhanVien = luong.MaNhanVien;
                if (int.Parse(up.LuongSauCapNhat.ToString()) != 0)
                {
                    l.LuongToiThieu = up.LuongSauCapNhat;
                }

                l.BHXH = luong.BHXH == null ? 0 : luong.BHXH;
                l.BHYT = luong.BHYT == null ? 0 : luong.BHYT;
                l.BHTN = luong.BHTN == null ? 0 : luong.BHTN;
             //   l.PhuCap = luong.PhuCap;
                l.ThueThuNhap = luong.ThueThuNhap;
                l.HeSoLuong = luong.HeSoLuong;

                //tao table luu lai moi lan cap nhat luong
                CapNhatLuong capNhat = new CapNhatLuong();
                capNhat.NgayCapNhat = DateTime.Now.Date;
                capNhat.MaNhanVien = luong.MaNhanVien;
                capNhat.LuongHienTai = luong.LuongToiThieu;
                capNhat.LuongSauCapNhat = up.LuongSauCapNhat;
                capNhat.BHXH = luong.BHXH;
                capNhat.BHYT = luong.BHYT;
                capNhat.BHTN = luong.BHTN;
              //  capNhat.PhuCap = luong.PhuCap;
                capNhat.ThueThuNhap = luong.ThueThuNhap;
                capNhat.HeSoLuong = luong.HeSoLuong;

                db.CapNhatLuongs.Add(capNhat);
                db.SaveChanges();
            }

            return Redirect("/admin/QuanLyLuong");
        }
        //end update lương

        public ActionResult ThanhToanLuong()
        {
            var luong = db.Luongs.ToList();

            DateTime now = DateTime.Now;
            foreach (var item in luong)
            {
                ChiTietLuong ct = new ChiTietLuong();
                ct.MaChiTietBangLuong = "t" + now.Month.ToString() + "/" + now.Year.ToString();
                ct.MaNhanVien = item.MaNhanVien;
                var ctl = db.ChiTietLuongs.Where(n => n.MaNhanVien == ct.MaNhanVien).FirstOrDefault();
                //ct.MaChiTietBangLuong = t+dem.ToString();

                double tienthue = 0, phucap = 0;
                double tong = 0;
                item.HeSoLuong = item.HeSoLuong == null ? 0 : item.HeSoLuong;
                ct.LuongCoBan = item.LuongToiThieu * (double)item.HeSoLuong;

                item.BHXH = item.BHXH == null ? 0 : item.BHXH;
                ct.BHXH = item.BHXH * item.LuongToiThieu / 100;

                item.BHYT = item.BHYT == null ? 0 : item.BHYT;
                ct.BHYT = item.BHYT * item.LuongToiThieu / 100;

                item.BHTN = item.BHTN == null ? 0 : item.BHTN;
                ct.BHTN = item.BHTN * item.LuongToiThieu / 100;


                item.PhuCap = item.PhuCap == null ? 0 : item.PhuCap;
                phucap = item.LuongToiThieu * (double)item.PhuCap;
                ct.PhuCap = phucap;


                item.ThueThuNhap = item.ThueThuNhap == null ? 0 : item.ThueThuNhap;
                tienthue = item.LuongToiThieu * (int)item.ThueThuNhap / 100;
                ct.ThueThuNhap = tienthue;

                ct.NgayNhanLuong = DateTime.Now.Date;
               
               
                tong = tong + ct.LuongCoBan - (double)(ct.BHXH + ct.BHYT + ct.BHTN) - (double)ct.ThueThuNhap + (double)ct.PhuCap;
                ct.TongTienLuong = tong.ToString();
                if (ctl == null || (ctl != null && ctl.NgayNhanLuong != ct.NgayNhanLuong))
                {
                    db.ChiTietLuongs.Add(ct);
                }
                ViewBag.ok = "Thanh toán thành công";
                db.SaveChanges();
            }
            return Redirect("/admin/QuanLyLuong");
        }


        public ActionResult ThanhToanMotNhanVien(String id)
        {
            var nv = db.NhanViens.Where(n => n.MaNhanVien == id).FirstOrDefault();
            if (nv != null)
            {
                //tim xem da co trong chi tiet lương chưa
                var ctl = db.ChiTietLuongs.Where(n => n.MaNhanVien == id).FirstOrDefault();
                //tìm bảng lương tương ứng với nhân viên
                var luongthang = db.Luongs.Where(n => n.MaNhanVien == id).FirstOrDefault();
                ChiTietLuong ct = new ChiTietLuong();
                DateTime now = DateTime.Now;
                double tienthue = 0, tong = 0, phucap = 0;

                ct.MaChiTietBangLuong = "t" + now.Month.ToString();
                ct.MaNhanVien = luongthang.MaNhanVien;

                ct.LuongCoBan = luongthang.LuongToiThieu * (double)luongthang.HeSoLuong;

                luongthang.BHXH = luongthang.BHXH == null ? 0 : luongthang.BHXH;
                ct.BHXH = luongthang.BHXH * luongthang.LuongToiThieu / 100;

                luongthang.BHYT = luongthang.BHYT == null ? 0 : luongthang.BHYT;
                ct.BHYT = luongthang.BHYT * luongthang.LuongToiThieu / 100;

                luongthang.BHTN = luongthang.BHTN == null ? 0 : luongthang.BHTN;
                ct.BHTN = luongthang.BHTN * luongthang.LuongToiThieu / 100;

                luongthang.PhuCap = luongthang.PhuCap == null ? 0 : luongthang.PhuCap;
                phucap = luongthang.LuongToiThieu * (double)luongthang.PhuCap;
                ct.PhuCap = phucap;


                luongthang.ThueThuNhap = luongthang.ThueThuNhap == null ? 0 : luongthang.ThueThuNhap;
                tienthue = (double)luongthang.LuongToiThieu * (double)luongthang.ThueThuNhap / 100;
                ct.ThueThuNhap = (double)tienthue;
                ct.NgayNhanLuong = DateTime.Now.Date;
                ct.TienThuong = 0;
                ct.TienPhat = 0;
                tong = tong + ct.LuongCoBan - (double)(ct.BHXH + ct.BHYT + ct.BHTN) - (double)ct.ThueThuNhap + (double)ct.PhuCap;
                ct.TongTienLuong = tong.ToString();
                if (ctl == null || (ctl != null && ctl.NgayNhanLuong != ct.NgayNhanLuong))
                {
                    ViewBag.ok = "Thanh toán thành công";
                    db.ChiTietLuongs.Add(ct);
                }
                db.SaveChanges();

            }
            return Redirect("/admin/QuanLyLuong");
        }

        public ActionResult DanhSachNhanLuong()
        {
            var list = db.ChiTietLuongs.ToList();
            return View(list);
        }
        public ActionResult XuatFileLuong(String id)
        {
            //var l = db.ChiTietLuongs.Where(n => n.MaChiTietBangLuong == id).ToList();
            var ds = db.ChiTietLuongs.ToList();
            //===================================================
            DataTable dt = new DataTable();
            //Add Datacolumn
            DataColumn workCol = dt.Columns.Add("Mã nhân viên", typeof(String));
            dt.Columns.Add("Lương cơ bản", typeof(String));
            dt.Columns.Add("BHXH", typeof(String));
            dt.Columns.Add("Phụ cấp", typeof(String));
            dt.Columns.Add("Tiền thưởng", typeof(String));
            dt.Columns.Add("Tiền phạt", typeof(String));
            dt.Columns.Add("Thuế thu nhập", typeof(String));
            dt.Columns.Add("Ngày nhận lương", typeof(String));
            dt.Columns.Add("Thực lãnh", typeof(String));

            //Add in the datarow


            foreach (var item in ds)
            {
                DataRow newRow = dt.NewRow();
                newRow["Mã nhân viên"] = item.MaNhanVien;
                newRow["Lương cơ bản"] = item.LuongCoBan;
                newRow["BHXH"] = item.BHXH;
                newRow["Phụ cấp"] = item.PhuCap;
                newRow["Tiền thưởng"] = item.TienThuong;
                newRow["Tiền phạt"] = item.TienPhat;
                newRow["Thuế thu nhập"] = item.ThueThuNhap;
                newRow["Ngày nhận lương"] = item.NgayNhanLuong;
                newRow["Thực lãnh"] = item.TongTienLuong;


                dt.Rows.Add(newRow);
            }

            //====================================================
            var gv = new GridView();
            //gv.DataSource = ds;
            gv.DataSource = dt;
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;

            Response.AddHeader("content-disposition", "attachment; filename=danh-sach-luong.xls");
            Response.ContentType = "application/ms-excel";

            Response.Charset = "";
            StringWriter objStringWriter = new StringWriter();
            HtmlTextWriter objHtmlTextWriter = new HtmlTextWriter(objStringWriter);

            gv.RenderControl(objHtmlTextWriter);
            Response.Output.Write(objStringWriter.ToString());
            Response.Flush();
            Response.End();
            return Redirect("/admin/QuanLyLuong");
        }


        public ActionResult QuaTrinhTangLuong(String id)
        {

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/Index.cshtml
@{
    ViewBag.Title = "Lương nhân viên";
}
@{
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
}
@using QuanLyNhanSu.Models
@model List<Luong>

<div class="container-fluid">
    <div class="">
        <div class="">
            <h1 class="page-header">
                Lương nhân viên
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
                </li>
                <li>
                    <i class="fa fa-money"></i> Lương
                </li>
            </ol>
        </div>
    </div>

    <div style="margin:10px">
        <a class="btn btn-primary" href="@Url.Action("XuatFileLuong", "QuanLyLuong", new {@id = "" })">
            Xuất file
        </a>
        <a class="btn btn-primary" href="@Url.Action("DanhSachNhanLuong", "ChiTietLuongs")">Danh sách nhận lương</a>
        <a class="btn btn-primary" href="@Url.Action("ThanhToanLuong", "QuanLyLuong")">Tính lương</a>
    </div>
    <div class="table-responsive">
        <table id="table-taikhoan" class="table  table-striped table-hover table-bordered ">
            <thead>
                <tr class="success">
                    <th>Mã nhân viên</th>
                    @*<th>Tên Nhân Viên</th>*@
                    <th>Lương tối thiểu</th>
                    <th>Hệ số lương</th>
                    <th>Phụ cấp CV</th>
                    <th>Tiền bảo hiểm</th>
                    <th>Tổng lương</th>
                    <th>Số bảng lương: @Model.Count</th>

                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.MaNhanVien</td>
                            @*<td>
                                @item.NhanVien.TenNhanVien
                            </td>*@
                            <td>
                                @string.Format("{0:#,#}", @item.LuongToiThieu).Replace(",", ",")
                            </td>
                            <td>
                                @item.HeSoLuong
                            </td>
                            <td>
                                @item.PhuCap
                            </td>
                            <td>
                                <table class="table table-bordered">
                                    <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                                    <tr>
                                        <td>@item.BHXH</td>
                                        <td>@item.BHYT</td>
                                        <td>@item.BHTN</td>
                                    </tr>
                                </table>

                            </td>
                            <td>
                                @{
                                    var luong = db.Luongs.ToList();
                                    double tong = 0;

                                    double tienthue = 0, phucap = 0, luongcb = 0, xh = 0, yt = 0, tn = 0;

                                    item.HeSoLuong = item.HeSoLuong == null ? 0 : item.HeSoLuong;
                                    luongcb = item.LuongToiThieu * (double)item.HeSoLuong;

                                    item.BHXH = item.BHXH == null ? 0 : item.BHXH;
                                    xh = (double)item.BHXH * item.LuongToiThieu / 100;

                                    item.BHYT = item.BHYT == null ? 0 : item.BHYT;
                                    yt = (double)item.BHYT * item.LuongToiThieu / 100;

                                    item.BHTN = item.BHTN == null ? 0 : item.BHTN;
                                    tn = (double)item.BHTN * item.LuongToiThieu / 100;


                                    item.PhuCap = item.PhuCap == null ? 0 : item.PhuCap;
                                    phucap = item.LuongToiThieu * (double)item.PhuCap;

                                    item.ThueThuNhap = item.ThueThuNhap == null ? 0 : item.ThueThuNhap;
                                    tienthue = item.LuongToiThieu * (int)item.ThueThuNhap / 100;

                                    tong = tong + (double)luongcb - (double)(xh + yt + tn) - (double)tienthue + (double)phucap;

                                }
                                @string.Format("{0:#,#}", @tong).Replace(",", ",") vnđ
                            </td>
                            <td>
                                <a class="btn btn-danger" href="@Url.Action("XoaUser", "QuanLyUser", new { @id = @item.MaNhanVien })"><i class="fa fa-trash-o"></i>&nbsp;Xoá</a>
                                <a class="btn btn-warning" href="@Url.Action("SuaBangLuong", "QuanLyLuong", new { @id = @item.MaNhanVien })"><i class="fa fa-pencil-square-o x5" aria-hidden="true"></i>&nbsp;Sửa</a>
                                <a class="btn btn-info" href="@Url.Action("ThanhToanMotNhanVien", "QuanLyLuong", new { @id = @item.MaNhanVien })">Tính lương</a>
                                @*<a class="btn btn-primary" href="@Url.Action("QuaTrinhTangLuong", "QuanLyLuong", new  {@id = @item.MaNhanVien })">Quá trình lương</a>*@
                            </td>
                        </tr>

                    }

                }

            </tbody>
        </table>
    </div>

</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/QuaTrinhTangLuong.cshtml
@model IEnumerable<QuanLyNhanSu.Models.CapNhatLuong>

@{
    ViewBag.Title = "Quá trình";
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Cập nhật bảng lương nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i><a href="@Url.Action("index","QuanLyLuong")">Lương</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Quá trình lương
            </li>
        </ol>
    </div>
</div>
<div class="table-responsive">
    <table id="table-taikhoan" class="table  table-striped table-hover table-bordered ">
        <thead>
            <tr class="success">
                <th>
                    Mã nhân viên
                </th>
                <th>
                    Lương trước khi cập nhật
                </th>
                <th>
                    Lương sau khi cập nhật
                </th>
               
                <th>
                    @Html.DisplayNameFor(model => model.BHXH)
                </th>
                <th>
                    Hệ số lương
                </th>
                <th>
                    Thuế thu nhập
                </th>
                <th>
                    Ngày áp dụng
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Luong.MaNhanVien)
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.LuongHienTai).Replace(",", ",")
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.LuongSauCapNhat).Replace(",", ",")
                     
                    </td>
                    <td>
                        @*@string.Format("{0:#,#}", @item.BHXH).Replace(",", ",")*@
                        <table class="table table-bordered">
                            <tr><th>XH</th><th>YT</th><th>TN</th></tr>
                            <tr>
                                <td>@item.BHXH</td>
                                <td>@item.BHYT</td>
                                <td>@item.BHTN</td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        @item.HeSoLuong
                        @*@string.Format("{0:#,#}", @item.PhuCap).Replace(",", ",")*@
                    </td>
                    <td>
                        @string.Format("{0:#,#}", @item.ThueThuNhap).Replace(",", ",")
                    </td>
                    <td>
                        @String.Format("{0:dd/MM/yyyy}", @item.NgayCapNhat)
                    </td>
                 
                </tr>
            }
        </tbody>
    </table>
</div>

QuanLyNhanSu/Areas/admin/Views/QuanLyLuong/SuaBangLuong.cshtml
@using QuanLyNhanSu.Models
@model Luong

@{
    ViewBag.Title = "Sửa lương nhân viên";
}



<div class="">
    <div class="">
        <h1 class="page-header">
            Cập nhật bảng lương nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i><a href="@Url.Action("index","QuanLyLuong")">Lương</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Cập nhật lương nhân viên
            </li>
        </ol>
    </div>
</div>
<div class="">
    <div class=" col-md-6 col-md-offset-3">
        @Html.AntiForgeryToken()

        <form class="form-horizontal" @Url.Action("SuaBangLuong", "QuanLyLuong") method="post" role="form">

            @Html.ValidationSummary(true)
            @*@Html.HiddenFor(model => model.MaNhanVien)*@

            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Mã nhân viên</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="MaNhanVien"
                           type="text"
                           value="@Model.MaNhanVien"
                           readonly />
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.MaNhanVien)
                    </label>

                </div>
                <!--end-->
            </div>
            <!--luong hien tai-->
            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Lương hiện tại</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="LuongToiThieu"
                           type="number"
                           value="@Model.LuongToiThieu"
                           readonly />
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.LuongToiThieu)
                    </label>

                </div>
                <!--end-->
            </div>

            <!--sau khi cap nhat-->
            @{
                QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
                CapNhatLuong c = new CapNhatLuong();
            }
            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Cập nhật lương</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="LuongSauCapNhat"
                           type="number"
                           pattern="[1-9](?:\d*)?\d+"
                           title="nhập tiền lương"
                           value="@Model.LuongToiThieu"
                           required />
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @*@Html.ValidationMessageFor(c => c.LuongSauCapNhat)*@
                    </label>

                </div>
                <!--end-->
            </div>

            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Hệ số lương</label>
                </div>
                <div class="col-sm-8">
                    @{
                        if (Model.NhanVien.TrinhDoHocVan.MaTrinhDoHocVan.Equals("gs"))
                        {

                            <select name="HeSoLuong" class="form-control">
                                @foreach (var item in db.LuongA31GS)
                                {
                                    if (item.HeSo == Model.HeSoLuong)
                                    {
                                        <option value="@item.HeSo" selected>@item.HeSo</option>
                                    }
                                    <option value="@item.HeSo">@item.HeSo</option>
                                }
                                @*<option value="6.2">6.2</option>
                                    <option value="6.56">6.56</option>
                                    <option value="6.92">6.92</option>
                                    <option value="7.28">7.28</option>
                                    <option value="7.64">7.64</option>
                                    <option value="8">8</option>*@
                            </select>
                        }
                        else if (Model.NhanVien.TrinhDoHocVan.MaTrinhDoHocVan.Equals("pgs"))
                        {
                            <select name="HeSoLuong" class="form-control">
                                @foreach (var item in db.LuongA21PGS)
                                {
                                    if (item.HeSo == Model.HeSoLuong)
                                    {
                                        <option value="@item.HeSo" selected>@item.HeSo</option>
                                    }
                                    <option value="@item.HeSo">@item.HeSo</option>
                                }
                                @*<option value="2.34">4.4</option>
                                    <option value="2.67">4.74</option>
                                    <option value="3">5.08</option>
                                    <option value="3.33">5.42</option>
                                    <option value="3.66">5.76</option>
                                    <option value="3.99">6.1</option>
                                    <option value="4.32">6.44</option>
                                    <option value="4.65">6.78</option>*@
                            </select>
                        }
                        else
                        {
                            <select name="HeSoLuong" class="form-control">
                                @foreach (var item in db.LuongA1GV)
                                {
                                    if (item.HeSo == Model.HeSoLuong)
                                    {
                                        <option value="@item.HeSo" selected>@item.HeSo</option>
                                    }
                                    <option value="@item.HeSo">@item.HeSo</option>
                                }
                                @*<option value="2.34">2.34</option>
                                    <option value="2.67">2.67</option>
                                    <option value="3">3.0</option>
                                    <option value="3.33">3.33</option>
                                    <option value="3.66">3.66</option>
                                    <option value="3.99">3.99</option>
                                    <option value="4.32">4.32</option>
                                    <option value="4.65">4.65</option>
                                    <option value="4.98">4.98</option>*@
                            </select>
                        }
                    }

                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.HeSoLuong)
                    </label>

                </div>
                <!--end-->
            </div>
            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Bảo hiểm xã hội</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="BHXH"
                           type="text"
                           value="@Model.BHXH" />

                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.BHXH)
                    </label>

                </div>
                <!--end-->

            </div>
            <!--BHYT-->
            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Bảo hiểm y tế</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="BHYT"
                           type="text"
                           value="@Model.BHYT" />

                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.BHYT)
                    </label>

                </div>
                <!--end-->

            </div>
            <!--BHTN-->
            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Bảo hiểm tự nguyện</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="BHTN"
                           type="text"
                           value="@Model.BHTN" />

                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.BHTN)
                    </label>

                </div>
                <!--end-->

            </div>
            <!--phu cap-->
            <div class="form-group hidden">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Phụ cấp</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="PhuCap"
                           type="number"
                           value="@Model.PhuCap" />
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.PhuCap)
                    </label>

                </div>
                <!--end-->

            </div>

            <div class="form-group">
                <!--start-->
                <div class="col-sm-4 control-label">
                    <label>Thuế thu nhập cá nhân</label>
                </div>
                <div class="col-sm-8">
                    <input class="form-control"
                           name="ThueThuNhap"
                           type="number"
                           value="@Model.ThueThuNhap" />
                </div>
                <div class="col-sm-offset-4 col-sm-5" style="height:15px">
                    <label class="control-label text-danger">
                        @Html.ValidationMessageFor(model => model.ThueThuNhap)
                    </label>

                </div>
                <!--end-->

            </div>

            <div class="form-group">
                <div class=" col-sm-offset-4 col-sm-5">
                    <input type="submit" value="Lưu lại" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
@*<div>
        @Html.ActionLink("Quay lại", "Index")
    </div>*@