QuanLyNhanSu/Models/KhenThuong.cs
namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class KhenThuong
    {
        //public KhenThuong() { 
        //    KTDetails = new HashSet<KhenThuongDetails>();
        //}

        [Key]
        [StringLength(30)]
        public string MaNhanVien { get; set; }

        public DateTime ThangThuong { get; set; }

        public string LyDo { get; set; }

        public int? TienThuong { get; set; }

        //public virtual ICollection<KhenThuongDetails> KTDetails { get; set; }

        public virtual NhanVien NhanVien { get; set; }
      
    }
}

QuanLyNhanSu/Models/KhenThuongViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QuanLyNhanSu.Models
{
    public class KhenThuongViewModel
    {
        public List<string> Thang { get; set; }
        public List<int> SoLuongKhenThuong { get; set; }
        public List<int> SoLuongKyLuat { get; set; }
        public List<string> TenNhanVien { get; set; }
        public List<int?> SoTienThuong { get; set; }
    }
}

QuanLyNhanSu/Areas/admin/Controllers/KhenThuongController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DocumentFormat.OpenXml.Bibliography;
using QuanLyNhanSu.Models;

namespace QuanLyNhanSu.Areas.admin.Controllers
{
    public class KhenThuongController : Controller
    {

        QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
        //
        // GET: /admin/KhenThuong/
        public ActionResult Index()
        {
            var t = db.KhenThuongs.ToList();
            return View(t);
        }
        [HttpGet]
        public ActionResult khen()
        {
            var nv = db.NhanViens.ToList();

            return View(new KhenThuong());
        }
        [HttpPost]
        public ActionResult khen(KhenThuong kt)
        { 
            KhenThuong ad = new KhenThuong();
            ad.MaNhanVien = kt.MaNhanVien;
            ad.ThangThuong = kt.ThangThuong;
            ad.TienThuong = kt.TienThuong;
            ad.LyDo = kt.LyDo;
            //--Thêm tiền thưởng
            var thangThuongM = kt.ThangThuong.Month;
            var thangThuongY = kt.ThangThuong.Year;

           
            var ct = db.ChiTietLuongs.Where(n => n.MaNhanVien == kt.MaNhanVien && n.NgayNhanLuong.Month == kt.ThangThuong.Month && n.NgayNhanLuong.Year == kt.ThangThuong.Year).FirstOrDefault();
            if(ct == null )
            {
                ViewBag.error = "Tháng này chưa có lương";
            }
            else
            {
                int currentTongTienLuong = 0;
                if (!string.IsNullOrEmpty(ct.TongTienLuong))
                {
                    int.TryParse(ct.TongTienLuong, out currentTongTienLuong);
                }

                int tienthuongValue = kt.TienThuong ?? 0; 
               
                int updatedTongTienLuong = currentTongTienLuong + tienthuongValue;
            
                ct.TienThuong = (ct.TienThuong ?? 0) + tienthuongValue;
                ct.TongTienLuong = updatedTongTienLuong.ToString();

                // Lưu thay đổi vào cơ sở dữ liệu
                db.Entry(ct).State = EntityState.Modified;
            }
            

            db.KhenThuongs.Add(ad);
            db.SaveChanges();
            return Redirect("/admin/KhenThuong");
        }

        public ActionResult xoaKhenThuong(String id)
        {
            var kt = db.KhenThuongs.Where(x => x.MaNhanVien == id).FirstOrDefault();
            
            //--Xoa tien thuong 
            var ct = db.ChiTietLuongs.Where(n => n.MaNhanVien == id).FirstOrDefault();

            if (ct == null)
            {
                ViewBag.error = "Không tìm thấy thông tin chi tiết lương.";
                return Redirect("~/admin/KhenThuong");
            }

            int currentTongTienLuong = 0;
            if (!string.IsNullOrEmpty(ct.TongTienLuong))
            {
                int.TryParse(ct.TongTienLuong, out currentTongTienLuong);
            }

            int tienthuongValue = kt.TienThuong ?? 0;
            int updatedTongTienLuong = currentTongTienLuong - tienthuongValue;

            // Đặt TienThuong về 0
            ct.TienThuong = 0;
            ct.TongTienLuong = updatedTongTienLuong.ToString();

            // Lưu thay đổi vào cơ sở dữ liệu
            db.Entry(ct).State = EntityState.Modified;
            //
            db.KhenThuongs.Remove(kt);
            db.SaveChanges();
            return Redirect("~/admin/KhenThuong");

        }
        public ActionResult KhenThuongChart()
        {
            var khenThuongData = db.KhenThuongs
                 .GroupBy(k => new { k.ThangThuong.Year, k.ThangThuong.Month })
                 .Select(g => new
                 {
                     Thang = g.Key.Month + "/" + g.Key.Year,
                     SoLuongKhenThuong = g.Count(),
                 })
                 .OrderBy(x => x.Thang)
                 .ToList();

            var kyLuatData = db.KyLuats
                .GroupBy(k => new { k.ThangKiLuat.Year, k.ThangKiLuat.Month })
                .Select(g => new
                {
                    Thang = g.Key.Month + "/" + g.Key.Year,
                    SoLuongKyLuat = g.Count(),
                })
                .OrderBy(x => x.Thang)
                .ToList();

            var allMonths = khenThuongData.Select(x => x.Thang)
                .Union(kyLuatData.Select(x => x.Thang))
                .Where(x => !string.IsNullOrEmpty(x)) // Lọc bỏ các chuỗi rỗng
                .OrderBy(x =>
                {
                    DateTime dateTime;
                    if (DateTime.TryParseExact(x, "mm/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out dateTime))
                    {
                        return dateTime;
                    }
                    return DateTime.MinValue; // Trả về giá trị mặc định nếu không thể chuyển đổi
                })
                .ToList();

            var viewModel = new KhenThuongViewModel
            {
                Thang = allMonths,
                SoLuongKhenThuong = new List<int>(),
                SoLuongKyLuat = new List<int>()
            };

            foreach (var month in allMonths)
            {
                var khenThuongCount = khenThuongData.FirstOrDefault(x => x.Thang == month)?.SoLuongKhenThuong ?? 0;
                var kyLuatCount = kyLuatData.FirstOrDefault(x => x.Thang == month)?.SoLuongKyLuat ?? 0;

                viewModel.SoLuongKhenThuong.Add(khenThuongCount);
                viewModel.SoLuongKyLuat.Add(kyLuatCount);
            }

            return View(viewModel);
        }


    }
}

QuanLyNhanSu/Areas/admin/Views/KhenThuong/Index.cshtml
@model IEnumerable<QuanLyNhanSu.Models.KhenThuong>

@{
    ViewBag.Title = "Danh sách khen thưởng";
}


<div class="">
    <div class="">
        <h1 class="page-header">
            Khen thưởng nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-gift"></i> Khen thưởng
            </li>
        </ol>
    </div>
</div>


<div style="margin:10px">

    <a class="btn btn-primary" href="@Url.Action("khen", "KhenThuong")">Khen Thưởng</a>
</div>

<table id="table-taikhoan" class="table table-responsive table-bordered table-striped">
    <thead>
        <tr class="success">
            <th>
                Mã Nhân viên
            </th>
            <th>
                Tháng thưởng
            </th>
            <th>
                Lý do
            </th>
            <th>
                Tiền thưởng
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NhanVien.MaNhanVien)
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", @item.ThangThuong)
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LyDo)
                </td>
                <td>
                    @string.Format("{0:#,#}", @item.TienThuong).Replace(",", ",")
                    
                </td>
                <td>
                    <a class="btn btn-danger" href="@Url.Action("xoaKhenThuong", "KhenThuong", new { @id = @item.MaNhanVien })"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

QuanLyNhanSu/Areas/admin/Views/KhenThuong/KhenThuongChart.cshtml
@model QuanLyNhanSu.Models.KhenThuongViewModel

@{
    ViewBag.Title = "Khen thưởng/Kỷ luật";
}
<style>
    h2{
        width :100%;
        text-align: center;
        border: 1px solid black;
        border-radius: 10px;
        margin-top: 20px;
    }
</style>

<h2 style="align-content: center;">Khen Thưởng/Kỷ Luật Nhân Viên</h2>

<canvas id="khenThuongKyLuatChart" width="400" height="200"></canvas>

@section scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    <script>
        $(document).ready(function () {
            var ctx = document.getElementById('khenThuongKyLuatChart').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: @Html.Raw(Json.Encode(Model.Thang)),
                    datasets: [{
                        label: 'Khen Thưởng',
                        backgroundColor: 'rgba(54, 162, 235, 0.5)',
                        borderColor: 'rgba(54, 162, 235, 1)',
                        borderWidth: 1,
                        data: @Html.Raw(Json.Encode(Model.SoLuongKhenThuong)),
                    }, {
                        label: 'Kỷ Luật',
                        backgroundColor: 'rgba(255, 99, 132, 0.5)',
                        borderColor: 'rgba(255, 99, 132, 1)',
                        borderWidth: 1,
                        data: @Html.Raw(Json.Encode(Model.SoLuongKyLuat)),
                    }]
                },
                options: {
                    scales: {
                        xAxes: [{
                            ticks: {
                                callback: function (value, index, values) {
                                    var parts = value.split("/");
                                    return parts[0] + "/" + parts[1]; // Hiển thị cả phần tháng và phần năm
                                }
                            }
                        }],
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1
                            }
                        }]
                    }
                }
            });
        });
    </script>
}

QuanLyNhanSu/Areas/admin/Views/KhenThuong/khen.cshtml
@*@model QuanLyNhanSu.Models.KhenThuong*@

@using QuanLyNhanSu.Models
@model KhenThuong

@{
    ViewBag.Title = "Khen thưởng";
    QuanLyNhanSuEntities db = new QuanLyNhanSuEntities();
    var nhanvien = db.NhanViens.Where(n => n.MaNhanVien != "admin").ToList();
}

<div class="">
    <div class="">
        <h1 class="page-header">
            Khen thưởng nhân viên
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i> <a href="@Url.Action("index","Admin")">Tổng quan</a>
            </li>
            <li>
                <i class="fa fa-money"></i> Khen thưởng
            </li>
        </ol>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="col-md-offset-2 col-md-8">
        <div class="form-horizontal">

            @Html.ValidationSummary(true)

            <div class="form-group">
                <div class="control-label col-md-offset-1 col-md-4 col-sm-4">
                    <label>Nhân viên</label>
                </div>
                <div class="col-md-4 col-sm-8">
                    @*@Html.DropDownList("@ViewBag.nhanvien", "ma nhan vien")*@

                    <input list="browsers" name="MaNhanvien" class="form-control">
                    <datalist id="browsers">
                        @foreach (var item in nhanvien)
                        {
                            <option value="@item.MaNhanVien.ToString()">@item.MaNhanVien - @item.HoTen</option>
                        }

                    </datalist>

                    @*<select name="MaNhanvien" class="form-control">
                    @foreach (var item in nhanvien)
                    {
                        <option value="@item.MaNhanVien.ToString()">@item.MaNhanVien - @item.HoTen</option>
                    }
                </select>*@
                    @Html.ValidationMessageFor(model => model.MaNhanVien)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Tháng thưởng</label>
                <div class="col-md-4 col-sm-8">
                    <input type="date" name="ThangThuong" required class="form-control" />

                    @Html.ValidationMessageFor(model => model.ThangThuong)
                </div>
            </div>
            <div class=" col-md-offset-5 col-sm-offset-4 col-sm-5" style="height:15px">
                <label class="control-label text-danger">
                    @ViewBag.error
                </label>
            </div>
            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Tiền thưởng(nếu có)</label>

                <div class="col-md-4 col-sm-8">
                    <input name="TienThuong" class="form-control" title="Tiền thưởng" />
                    @Html.ValidationMessageFor(model => model.TienThuong)
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-offset-1 col-md-4 col-sm-4">Lý do</label>

                <div class="col-md-4 col-sm-8">
                    @Html.TextAreaFor(model => model.LyDo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LyDo)
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-4 col-md-offset-5 col-sm-8">
                    <input type="submit" value="Xác nhận" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

<div class="clearfix"></div>